x <- read.table(file.choose("Assignment6Dataset.txt"),header=TRUE,sep=",")
print(x)
install.packages("plyr")
library(plyr)
y <- ddply(x,"Sex",transform, Grade.Average=mean(Grade))
write.table(y,"Sorted_Average")
write.table(y,"Sorted_Average",sep=",")
New <- subset(x, grepl("i", x$Name))
write.table(New,"DataSubset",sep=",")
